### ISSUE TITLE
can't play any song after install

### ISSUE THREAD

**Issue by Niclas1337** [down-bad/advanced-rpc#1]
I can't play a song anymore due to MusicKit error: "NO DRM".

This happens after installing the plugin and works again after uninstalling

**Comment by down-bad** [comment]
Hi, what version of Cider are you using?

**Comment by Niclas1337** [comment]
> Hi, what version of Cider are you using?

latest, 1.5.8 - beta 40

**Comment by down-bad** [comment]
I don't seem to be able to reproduce this issue. Are you sure the plugin is causing it? Could you attach the logs?

**Comment by alsoGAMER** [comment]
@UnbreakCode have you tried reinstalling widevinecdm? (Settings > Advanced > Experimental > Reinstall WidevineCDM)
also please keep in mind that beta versions aren't intended for production usage as they are expected to break (as also [stated](https://docs.cider.sh/support/disclaimer#support-nightly-beta-releases) by cider devs)

**Comment by Niclas1337** [comment]
was musickit issue at this time
