### ISSUE TITLE
Plugin for Cider 2

### ISSUE THREAD

**Issue by EduardoLozaRojas** [down-bad/advanced-rpc#10]
I was just wondering if you had any plans on bringing the plugin to Cider 2 whenever they support it ? 

Not sure if it's gonna take a lot of time to implement it but I think they're already giving devs small access to create plugins.

**Comment by down-bad** [comment]
Hey, I would be interested in doing that, if any Cider dev is willing to contact me, as I don't have access to their Discord server.

**Comment by EduardoLozaRojas** [comment]
https://discord.gg/KJSdpPzV Did you already try joining the server or is not working ?

**Comment by down-bad** [comment]
I was banned for calling out the owner for making misleading claims and deceiving users.

**Comment by Ilovemyhous** [comment]
Hey!
I asked on their Discord, and they'll unban you apparently, if they already didn't do by the time of writing.

Also, Cider 2 doesn't support plugins yet.

**Comment by cryptofyre** [comment]
Reaching out here to extend an invitation for your possible re-engagement with our project. Your prior contributions were valuable, and we would greatly appreciate your continued involvement!

Should you wish to revisit this opportunity, we can remove any existing bans/restrictions on your account. It would be particularly intriguing to witness your innovative ideas and contributions within the realm of plugins for Cider 2.0's newly implemented frameworks.

At your earliest convenience, please provide us with your Discord ID to facilitate the reinstatement process.

Thanks!

**Comment by down-bad** [comment]
Thank you for your invitation, looking forward to continue contributing for Cider. 
241929388403195914

**Comment by cryptofyre** [comment]
I am pleased to inform you that your account has been successfully reinstated. You should now have access to the Discord server once more.

Should you encounter any issues or if there's anything further you need assistance with, please feel free to reach out. We're always here to help!

**Comment by Ilovemyhous** [comment]
I think we can close this issue(?)

**Comment by down-bad** [comment]
unfortunately impossible with whatever their new client's backend, and the imamturity and uncooperativeness of the cider devs. ppl shouldn't be using cider nowadays anyways
