### ISSUE TITLE
Wrong year displayed(?)

### ISSUE THREAD

**Issue by Ilovemyhous** [down-bad/advanced-rpc#11]
Hello!
Not sure if this is intended behavior, but the plugin takes the original release date of the album, even of remixes.

Original album
![image](https://github.com/down-bad/advanced-rpc/assets/50217071/a45a20b4-f1f5-4aee-bd94-4d8302dc7c68)

Remaster
![image](https://github.com/down-bad/advanced-rpc/assets/50217071/daf9e2bc-a608-49bf-9fd7-752c8a08e85b)
![image](https://github.com/down-bad/advanced-rpc/assets/50217071/8240bf14-af71-4c0b-8884-36310c17cf52)

**Comment by down-bad** [comment]
Hey, the data is provided by Cider / Apple Music, so there isn't anything we can do about it sadly.

**Comment by Ilovemyhous** [comment]
Alright, I'll close this then, thanks for the clarification. 😃
