### ISSUE TITLE
Playback buttons do not work and is bugged

### ISSUE THREAD

**Issue by amidstacy** [down-bad/advanced-rpc#12]
video showing it:
https://github.com/down-bad/advanced-rpc/assets/71241425/4e2a2b7d-2f6c-4b78-84e1-4362ce0e8aa0

if the video doesn't work: https://streamable.com/a66yk4

edit: i also tried restarting cider, doesn't work. restarting discord didn't work either. tried on discord web, not working + a friend checked and none of the buttons work, sometimes you stay on the profile after clicking sometimes not

**Comment by amidstacy** [comment]
Oh, I forgot to update this thread- it works now! probably Discord's side.

**Comment by down-bad** [comment]
Ah, something's wrong with my notifications, I missed this. Yeah, buttons not working was Discord's problem (again).
