### ISSUE TITLE
[Feature] Change ActivityType from "Playing" to "Listening"

### ISSUE THREAD

**Issue by Lfmpaes** [down-bad/advanced-rpc#3]
I'm from Brazil, which means the majority of my friends speak Portuguese.

The RPC uses the ActivityType value of 0, which returns "Playing" to the user profile. However, in Portuguese the translation doesn't make much sense in the context of music, showing the equivalent of "Gaming" in English on my user card.

Even though "Playing" could be interpreted as both "playing music" and "playing game", in other languages it does not work quite well. Spotify uses the ActivityType value "2", which returns "Listening".

**Comment by down-bad** [comment]
Hey there. As far as I know, we cannot change the activity type due to Discord's limitations, and it is restricted to official integrations only (such as Spotify and Watch Together).
