### ISSUE TITLE
{year} variable doesn't work.

### ISSUE THREAD

**Issue by Ilovemyhous** [down-bad/advanced-rpc#4]
Cider version: 1.5.9
Plugin version: 1.5.0

What's actually happening, is that it shows the track number from the queue.

![image](https://user-images.githubusercontent.com/50217071/206145471-301b08c8-2fcc-45b7-b2cc-c1616f507890.png)
![image](https://user-images.githubusercontent.com/50217071/206145608-1af4f100-e17f-41cf-a4a1-67a21592ba90.png)
![image](https://user-images.githubusercontent.com/50217071/206145745-4c01d9d8-cee6-4331-a8bd-15a9f9fdd962.png)

I've already restarted Cider, but it doesn't fix it.

**Comment by down-bad** [comment]
Hey there, this is indeed a bug and will be fixed with the next update. Thank you for reporting!
