### ISSUE TITLE
Elapsed Time Resets when Paused

### ISSUE THREAD

**Issue by yourlocaldumbfoundedgay** [down-bad/advanced-rpc#5]
hi! just wanted to say this project is amazing; i always wanted to be able to have what i was listening to in apple music in my status like spotify :)
anyways, whenever i pause the song i'm listening to (which is quite often, because my airpods dont stay in my ear) and then unpause the song, the elapsed time resets to 0:00. otherwise, all other pause-related functions work fine.

**Comment by down-bad** [comment]
Hey, I'm glad you're enjoying it!
I'll look into it

**Comment by down-bad** [comment]
Fixed with 1.5.3
