### ISSUE TITLE
Shows paused status even when I've set to not show status when paused

### ISSUE THREAD

**Issue by lemonsked** [down-bad/advanced-rpc#8]
![image](https://user-images.githubusercontent.com/8615284/209883423-f9ceba8b-a723-4632-8d72-0a93b93f9c37.png)
This isn't even the song I was playing when I paused

**Comment by lemonsked** [comment]
Settings:
![image](https://user-images.githubusercontent.com/8615284/209883544-daadd953-18d7-470f-a0b6-4566c406d710.png)

**Comment by down-bad** [comment]
I see the animated artwork works now?
